name: Generate NZPortable Nightlies.
on:
  schedule:
  - cron: 0 7 * * *
  workflow_dispatch:

jobs:
  Generate-Nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get apt ready
        run: |
          sudo apt update
          sudo apt install -y zip unzip wget curl git jq
      - name: Assemble Switch package
        working-directory: ./
        run: ./generate-nightly.sh ${{ secrets.GITHUB_TOKEN }}
      - name: Get Build Date
        id: date
        run: echo "date=$(cat release_version.txt)" >> "$GITHUB_OUTPUT"
      - name: Delete Old Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait ...
        run: sleep 10
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: nightly
          body_path: changes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./out/nzportable-switch.zip
            ./out/build-version.txt
